const UiActionTypes = {
  TOGGLE_DRAWER_HIDDEN: "TOGGLE_DRAWER_HIDDEN",
  TOGGLE_DRAWER_ADMIN_HIDDEN: "TOGGLE_DRAWER_ADMIN_HIDDEN",
  TOGGLE_OREDERS: "TOGGLE_OREDERS",
  TOGGLE_PRODUCTS: "TOGGLE_PRODUCTS",
  TOGGLE_ANALYTICS: "TOGGLE_ANALYTICS",
  TOGGLE_MARKETING: "TOGGLE_MARKETING",
  TOGGLE_STORE: "TOGGLE_STORE",
};

export default UiActionTypes;
